### ISSUE TITLE
Go言語学習: コンソールで動作する数字ソートの作成をGo言語でする

### ISSUE THREAD

**Issue by camberbridge** [egroup-develop/sandbox#5]

**Comment by camberbridge** [comment]
・マージソートをGoで作成
・・比較対象は数字
・・標準入出力を使ってユーザーに2つの数字を提示
・・同じく標準入出力を使って「0か1」で2つの数字のうちどちらかを選択させる
・・ソートが終わるまで提示と選択を繰り返す
・・ソートが終わったら結果を表示

・完成したマージソートを基に必要なリクエストを考える
・・画像のURL以外にも画像添付元記事のURLが必要とか
・・画像収集の段階でどの情報が必要なのか

・必要なリクエストが決まり次第、原田さんと共有

**Comment by camberbridge** [comment]
- マージソート完了
- 実践編
  - Goのパッケージを駆使してマージソートを作る
    - HTTPリクエスト, JSONファイルの取得(解析), 正規表現, バリデーション 等

**Comment by camberbridge** [comment]
[Go パッケージ リスト](http://golang.jp/pkg)

**Comment by camberbridge** [comment]
[Git コマンド一覧](http://qiita.com/konweb/items/621722f67fdd8f86a017)

**Comment by camberbridge** [comment]
[Git コマンド チーム開発で使うコマンド一覧](https://gist.github.com/dtan4/5276185)

**Comment by camberbridge** [comment]
## 練習用
- [天気予報API](http://weather.livedoor.com/weather_hacks/) で練習しよう！
  - 特にこのURL( http://weather.livedoor.com/forecast/webservice/json/v1?city=200010 (ちなみに長野県の天気情報))をGo のHTTPリクエスト用パッケージのGETリクエストをする関数を使って送りましょう
  - 返ってくるJSONファイルを配列か何かに格納して手元で使えるようにしましょう
  - JSONファイルをGoのJSON解析パッケージを使って解析し、希望の情報(気温や天気や湿度 等)を手元で使えるようにしましょう(要は木の葉が欲しいのです)。具体的には下記の「翌日の日付, 天気, URL」を手元で使えるようにしましょう
    - forecasts: 
      - date: 翌日の日付
      - image: 
        - title: 天気
        - url: URL
  - この中で正規表現を駆使しましょう

**Comment by suzukakedaiki** [comment]
[GoでHTTP Trailerを扱う](http://qiita.com/ono_matope/items/89ce7f491b791dece38c)

**Comment by dktnk96** [comment]
[Go-langでJSON解析する方法](https://github.com/astaxie/build-web-application-with-golang/blob/master/ja/07.2.md)
解析されるデータの形式が事前に分からなかった場合はinterfaceで解析する
