### ISSUE TITLE
gulp学習

### ISSUE THREAD

**Issue by dktnk96** [egroup-develop/sandbox#6]

**Comment by camberbridge** [comment]
- 環境を整える(Windowsの人は [MinGW](http://www.mingw.org/) か [Cygwin](https://www.cygwin.com/) を導入してから)
- [gulp](http://gulpjs.com/) をやる
  - Plugin の使い方を覚える

**Comment by camberbridge** [comment]
参考
- [Gulp_gettingStarted](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md#getting-started)
- [Gulpおじさん](http://otiai10.hatenablog.com/entry/2014/06/05/221741)

**Comment by a2chub** [comment]
srcフォルダと、destフォルダを分けましょう。
gulpで、src>destにまとめるようにしましょう。

gulpで開発サーバをアップして、ライブリロード出来るようにしましょう。

**Comment by suzukakedaiki** [comment]
[Gulp ディレクトリ作成あれこれ](http://qiita.com/tomoki7/items/0e2e3e7694d855e0cbb9)

**Comment by camberbridge** [comment]
http://isee-web.net/?p=543

**Comment by dktnk96** [comment]
[Gulp 作業スペースあれこれ](http://qiita.com/tomoki7/items/0e2e3e7694d855e0cbb9)
[gulpでlivereloadしたい時の書き方](http://qiita.com/lion-man44/items/9b740aea439ef5643048)
[gulpでWebサーバー/ライブリロード](http://qiita.com/oreo3@github/items/f8ac551c5021c36ffd98)

**Comment by camberbridge** [comment]
[以下, 詳細](https://github.com/egroup-develop/findol_proto/commit/c2b5d5196aba64928d244eb35100166c755a926e)
- 作業用src/と公開用dist/を作成. 
  - gulpfile.jsに実装したもの
    - 開発サーバをアップしてlivereload
    - jsファイルの圧縮
    - ファイルの監視
    - watch時のエラーハンドリング
