### ISSUE TITLE
シナリオ作成、確認

### ISSUE THREAD

**Issue by dktnk96** [egroup-develop/sandbox#7]

**Comment by camberbridge** [comment]
#8 の前に、アイドルソートを行う過程をユーザーの立場に立って(フローチャートを)作成する

考慮する点
・一回のソートで、対象を最大50人に抑える

**Comment by natsu0801** [comment]
# FinDoLフローチャート (基本動作)
1.  ロガールを開く
2. FinDoLをタップ（クリック）して開く
3. ソートをする(大体3分程度)
4. グループ内で1～10位が決まる
5. 結果一覧の中から 気になった子の画像一覧を表示して閲覧する
6. 気に入った写真の記事をクリップする。

**Comment by natsu0801** [comment]
# LoGiRLもFinDoLも初めて使う人の場合
1. 自然検索でLoGIRLにたどり着く
2. LoGIRLを回遊して、FinDoLの導線にたどり着く
3. FinDoLの導線を押し、ページを開く
4. FinDoLの説明を読み、ソートを始める
5. ソートを行うが数回ソートしたのち離脱する

**Comment by natsu0801** [comment]
# ヘビーユーザー(10回以上使用者)
1. bookmarkからFinDoLに直接アクセスする
1. そのあとすぐにソート開始ボタンを押す
1. ソートをする(誰が登場するかが大体わかるから選ぶのが早い)
1. 1～10位が決まる
1. 結果一覧の中から上位の子の保存していない新しい記事だけをクリップする。

**Comment by natsu0801** [comment]
# すこし使った人(2・3回使用者)
1. 履歴からロガールにアクセスする。
1. ロガールを回遊した後、FinDoLの導線にたどり着く。
1. FinDoLの説明は読まずに、ソート開始ボタンを押す。
1. ソートする(ソートにかかる時間は初心者と同じくらい)
1. 1～10位が決まる
1. 結果一覧の中から画像一覧を表示して閲覧する
1. 結果一覧の中の気に入った写真の記事をたくさんクリップする

**Comment by natsu0801** [comment]
# シナリオまとめ
## 重要そうなところ
1. FinDoLの導線（設置場所・クリエイティブ）
1. FinDoLの説明
1. ソート画面のUI

**Comment by natsu0801** [comment]
# 忙しい人

**Comment by natsu0801** [comment]
# 暇な人

**Comment by natsu0801** [comment]
# LoGiRLのライトユーザでFinDoLを初めて使う人
1. 自然検索でLoGIRLにたどり着く
2. LoGiRLを回遊して、FinDoLの導線にたどり着く
3. FinDoLの導線を押す
4. FinDoLの説明を読み、ソートを始める
5. ソートを行うが数回ソートしたのち離脱する

**Comment by natsu0801** [comment]
# LoGiRLのヘビーユーザーでFinDoLを初めて使う人
1. bookmarkからLoGiRLに遷移する
2. LoGiRLを回遊して、FinDoLの導線にたどり着く
3. FinDoLの導線を押す
4. FinDoLの説明を読み、ソートを始める
5. ソートを行う
6. 結果ランキング1～10位が出る
7. 結果ランキングを一通り閲覧し、離脱

**Comment by natsu0801** [comment]
# LoGiRLのヘビーユーザーでFinDoLのライトユーザー

**Comment by natsu0801** [comment]
# FinDoLのみのライトユーザー(LoGiRLは使わない)
1. 自然検索でFinDoLに遷移
2. FinDoLの説明は読まずにソートを始める
3. ソートを行う
4. 結果ランキング1～10位が出る
5. 結果ランキングを一通り閲覧する
6. ソート開始画面に戻ってソートを数回繰り返す

**Comment by natsu0801** [comment]
# LoGiRLもFinDoLもライトユーザー
1. 自然検索でLoGiRLに遷移する
2. LoGiRLを回遊したのち、FinDoLの導線にたどり着く
3. FinDoLの説明は読まずにソートを始める
4. ソートを行う
5. 結果ランキング1～10位が出る
6. 結果ランキングを一通り閲覧する
7. ソート開始画面に戻ってソートを数回繰り返す

**Comment by natsu0801** [comment]
# LoGiRLのヘビーユーザーでFinDoLのライトユーザー
1. bookmarkからLoGiRLに遷移する
2. LoGiRLを回遊し、FinDoLの導線にたどり着く
3. FinDoLの説明は読まずにソートを始める
4. ソートを行う
5. 結果ランキング1～10位が出る
6. 結果ランキングを一通り閲覧する
7. 上位の子の画像一覧ページに遷移する
8. 更にその中で気に入った画像元の記事に遷移し閲覧する。

**Comment by natsu0801** [comment]
# FinDoLのみのヘビーユーザー

**Comment by natsu0801** [comment]
# LoGiRLのライトユーザーでFinDoLのヘビーユーザー
1. bookmarkからFinDoLに遷移する
2. FinDoLの説明は読まずにソートを始める
3. ソートを行う
4. 結果ランキング1～10位が出る
5. 結果ランキングを一通り閲覧する
6. 上位の子の画像一覧ページに遷移する
7. 更にその中で気に入った画像元の記事に遷移し閲覧する。
8. そのあと、オススメ一覧に遷移する
9. オススメ一覧を閲覧し、その一覧の中に気になる子がいるか確認する
10. 気になる子がいた場合、その子の記事を閲覧する

**Comment by natsu0801** [comment]
# LoGiRLもFinDoLもヘビーユーザー
1. bookmarkからLoGiRLに遷移する
2. LoGiRLで最新の記事などを閲覧した後、FinDoLの導線にたどり着く
3. FinDoLの説明は読まずにソートを始める
4. ソートを行う
5. 結果ランキング1～10位が出る
6. 結果ランキングを一通り閲覧した後、オススメ一覧に遷移する
7. オススメ一覧を閲覧し、その一覧の中に気になる子がいるか確認する
8. 気になる子がいた場合、その子の記事を閲覧する
9. さらにその記事が気に入った場合、クリップする

**Comment by natsu0801** [comment]
# FinDoLのみのヘビーユーザー(オススメ一覧を楽しみたい人)
1. bookmarkからFinDoLに遷移する
2. FinDoLの説明は読まずにソートを始める
3. ソートを行う
4. 結果ランキング1～10位が出る
5. 結果ランキングを一通り閲覧した後、オススメ一覧に遷移する
6. オススメ一覧を閲覧し、その一覧の中に気になる子がいるか確認する

**Comment by camberbridge** [comment]
[完成Ver.0](https://docs.google.com/presentation/d/1-9wasdmroYw3PsNKOxlRrvUVcltpGwefC0_ljLrRqAQ/edit#slide=id.gd22fd434b_0_0)
