### ISSUE TITLE
サイトマップを構築する

### ISSUE THREAD

**Issue by a2chub** [egroup-develop/sandbox#8]
本サービスがどんな画面があって
それぞれどういう風に接続されるのか？

管理画面側のなのか？
ユーザー側なのか？
考慮しながら作成する

**Comment by natsu0801** [comment]
【ユーザー側サイトマップ】
LoGiRL
　　◆FinDoL
　　　　▽グループ選択
　　　　　　・ソート

　　　　▽結果
　　　　　　・画像一覧

**Comment by natsu0801** [comment]
管理画面側のサイトマップ#とは

**Comment by camberbridge** [comment]
- [マインドマップ](https://www.mindmup.com/#m:g10B95K5_buI_bsQ0FQZDNZV2hpbmc)を使って詳しく書きましょう
  - 管理者画面側はマインドマップの左側にあたる
