### ISSUE TITLE
各画面デザインを起こす(UI作成)

### ISSUE THREAD

**Issue by a2chub** [egroup-develop/sandbox#9]
#8 にしたがいながら

各画面のデザインを起こす

**Comment by camberbridge** [comment]
- サイトマップにしたがいからページでいいので全ページ作る
- GitHubを利用してプロトタイプを作成
  - [findol_proto](https://github.com/egroup-develop/findol_proto)を自由に使って
  - [http://egroup-develop.github.io/findol_proto/](http://egroup-develop.github.io/findol_proto/)上で確認

**Comment by natsu0801** [comment]
サイトマップで出ているものは全てcomp上での作成・findol_protoへのアップは完了。
